# Generated by Django 4.2.7 on 2023-11-20 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='status',
            field=models.CharField(choices=[('Bought', 'Bought'), ('Given', 'Given'), ('Wish List', 'Wish List')], default='Pending', max_length=10),
        ),
    ]
