# Generated by Django 4.2.7 on 2023-11-23 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_gift_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gift',
            name='rating',
        ),
    ]
